// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhday-0Fd6YGl_cI071QaoXmJ44dz1BD0',
    appId: '1:410300077526:web:c143e7fb240e98f0610077',
    messagingSenderId: '410300077526',
    projectId: 'todo-app-by-dn',
    authDomain: 'todo-app-by-dn.firebaseapp.com',
    storageBucket: 'todo-app-by-dn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzGt1xcXx5HufVpBEmdzRhZeQ97tLiOeY',
    appId: '1:410300077526:android:33b419c2edd05601610077',
    messagingSenderId: '410300077526',
    projectId: 'todo-app-by-dn',
    storageBucket: 'todo-app-by-dn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-uSwCoEv_hrwuypPxui7DKZarhEhEnFs',
    appId: '1:410300077526:ios:8e1617e16666bcfb610077',
    messagingSenderId: '410300077526',
    projectId: 'todo-app-by-dn',
    storageBucket: 'todo-app-by-dn.appspot.com',
    iosClientId: '410300077526-vnpqf8udqk8848ofdpgj525uue65l88j.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppByDn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-uSwCoEv_hrwuypPxui7DKZarhEhEnFs',
    appId: '1:410300077526:ios:8e1617e16666bcfb610077',
    messagingSenderId: '410300077526',
    projectId: 'todo-app-by-dn',
    storageBucket: 'todo-app-by-dn.appspot.com',
    iosClientId: '410300077526-vnpqf8udqk8848ofdpgj525uue65l88j.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppByDn',
  );
}
